spring:
  application:
    name: eureka-server

server:
  port: 9000
    
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:${server.port}/eureka/    
 
management:
  context-path: /manage 
  security:
    enabled: false    

endpoints:
  sensitive: true
  shutdown:
    enabled: true
  restart:
    enabled: true
         
logging: 
  config: ${app.home}/${spring.application.name}/config/logback.xml
