spring:
  application:
    name: sms-service

server:
  port: 8081
  
eureka:
  instance:
    statusPageUrlPath: /manage/info
    healthCheckUrlPath: /manage/health
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
       defaultZone: http://localhost:9000/eureka

management:
  context-path: /manage 
  security:
    enabled: false    
    
endpoints:
  sensitive: true
  shutdown:
    enabled: true
  restart:
    enabled: true
    
logging: 
  config: ${app.home}/${spring.application.name}/config/logback.xml
 